name: examples

on:
  schedule:
    # At the end of everyday
    - cron: 0 0 * * *

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [ubuntu-20.04]

    runs-on: [self-hosted, Linux, Ubuntu20.04-public-pod16, pod16, public]
    container: 
      image: localhost:5000/graphcore/pytorch:3.2.0-EA.1-ubuntu-20.04
      options: --pull=always --ulimit memlock=-1:-1 --cap-add=IPC_LOCK --device=/dev/infiniband/ -e IPUOF_VIPU_API_HOST -e IPUOF_VIPU_API_PARTITION_ID --shm-size=128G
    env:
      POPTORCH_WAIT_FOR_IPU: 1
    timeout-minutes: 720
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        ref: sdk-release-3.2
    - name: Attach RDMA network 
      run: |
          python3 -m pip install docker
          python3 -c "import docker; client=docker.from_env(); client.networks.get('macvlan_rdma_swarm').connect(client.containers.get('${{ job.container.id }}'))"
          gc-monitor
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install .[testing]
    - name: Test with Pytest
      run: |
        export RUN_SLOW=true
        pytest tests/test_examples_match_transformers.py
        pytest tests/test_examples.py
